name: Go Test and Lint on dev push and main PRs

on:
  # Run this workflow on any pull request targeting main
  pull_request:
    branches:
      - main

  # Run this workflow on every push to the dev branch
  push:
    branches:
      - dev

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: allow write access to checks to allow the action to annotate code in the PR.
      checks: write

    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'  # or whichever version of Go you prefer

      # 3. (Optional) Cache Go modules for faster builds
      - name: Cache modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install dependencies
      - name: Install dependencies
        run: go mod download

      # 5. Run lint checks (golangci-lint-action)
      - name: Run lint checks
        uses: golangci/golangci-lint-action@v8.0.0

      # 7. Run Go tests
      - name: Run Go tests
        run: go test -v ./...
